### PR TITLE
Use Cstruct.check_alignment to perform that operation  :-)

### PR DESCRIPTION
**Pull request by Chris00**

### CODE REVIEW

**Comment by Chris00** [comment]
AppVeyor → time out.

**Comment by Chris00** [comment]
Cstruct ≥ 2.2.0 is only [available on OCaml ≥ 4.02.3](https://travis-ci.org/mirage/io-page/jobs/149840179#L543) which is a problem with the tests.

**Comment by djs55** [comment]
Thanks for the patch -- I'll change travis to use a more modern OCaml compiler.

**Comment by djs55** [comment]
Merged as part of #44 

Thanks for the patch -- sorry it took so long to merge!

**Pull request closed without merging**
