### PR TITLE
return CHAR array, as advertised in type t, fixes #17

### LINKED ISSUE #17: cstruct.to_bigarray is not equal after going through io_page
I encounter to run in a failed assertion (line 20) in https://github.com/hannesm/test -- which reproduces the code ocaml-crunch contains for reading data from its key-value store.

a string is put into an io_page, and a cstruct of the given string length is exposed -- the cstruct is not equal (using to_bigarray) to a cstruct produced by of_string of the initial string...

this problem occurs here on FreeBSD (seems to work fine on linux) with io-page 1.4.0 and 1.2.0 at least...

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by hannesm** [comment]
is there a way to find out from the C level which version of OCaml is running? 4.02 provides a `caml/version.h` -- which does not exist in 4.01.. (and 4.01 does not define `CAML_BA_CHAR`)... @yallop any hints?

**Comment by yallop** [comment]
I don't think there was anything in OCaml's headers before 4.02 that explicitly gives the version.  There's some discussion under [PR#6406](http://caml.inria.fr/mantis/view.php?id=6406).  However, there were a number of macros introduced along with the bigarray kind representation change.  It might not be completely unreasonable to use one of those as a proxy (e.g. `#ifdef Caml_ba_kind_val`):

```
$ git diff 4.01.0..4.02.1 otherlibs/bigarray/*.h | grep '#define'
+#define Caml_ba_kind_val(v) Int_val(v)
+#define Val_caml_ba_kind(k) Val_int(k)
+#define Caml_ba_layout_val(v) (Int_val(v) << CAML_BA_LAYOUT_SHIFT)
+#define Val_caml_ba_layout(l) Val_int(l >> CAML_BA_LAYOUT_SHIFT)
```

**Comment by hannesm** [comment]
thanks @yallop!
travis is now happy... and it is tested on my 4.02.1 system -- safe to merge

**Comment by avsm** [comment]
This same change needs to go into `mirage-platform` in `xen-ocaml/bindings/page_stubs.c` -- any chance of a corresponding pull there before merge?

**Comment by hannesm** [comment]
https://github.com/mirage/mirage-platform/pull/121 ...

**Comment by avsm** [comment]
@samoht or I are going to port this to remove the C binding from mirage-platform using @talex5's oasis compilation scheme.  That will remove the dangerous duplication of C stubs here.

**Comment by hannesm** [comment]
@avsm https://github.com/mirage/mirage-platform/pull/122 -- I used the TCP/IP C bits porting (https://github.com/mirage/mirage-platform/commit/5376e8c8abfb718eaaf5ab68715a37752969a2ce and https://github.com/mirage/mirage-tcpip/commit/e6dfacfe315fd445201eb0ed36e94b092fa31030#diff-0b6213b84518a662543be7b7516bc846R18) as example

**Comment by hannesm** [comment]
(and @talex5 can most likely point out issues I made while trying to do so)

**Comment by talex5** [comment]
It's worth diffing the C stubs to make sure we're not losing anything.

In particular, the mirage-platform version has:

    /* Explicitly zero the page before returning it */
    memset(block, 0, len);

**Comment by avsm** [comment]
Since we now have the requisite mirage and Oasis runes, I believe we should port io-page to supply the stubs to mirage-platform rather than continue the duplication.

**Comment by hannesm** [comment]
@avsm what do you mean? I removed the (duplicated) C code from mirage-platform, they live all in io-page now (apart from that it's now duplicated here due to the required memset on Xen)..

**Comment by talex5** [comment]
Perhaps it should memset on Unix too...

**Comment by avsm** [comment]
Apologies; I missed the corresponding mirage-platform removal commit.  I agree with @talex5 that it should have the same behaviour on Unix wrt page zeroing.

**Comment by hannesm** [comment]
I did so, and also tested both on unix and on xen!

**Pull request merged**
